### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Lauro112** [Amazon-Hate-it-But-Need-it/Amazon-AtoZ-VET-Flex-Bot#1]
hi
i get this error. i have tryied so many times but id ont know why. i am using windows 11 with python 312

C:\Python312>python.exe AtoZ-Bot.py
Traceback (most recent call last):
  File "C:\Python312\AtoZ-Bot.py", line 177, in <module>
    main()
  File "C:\Python312\AtoZ-Bot.py", line 165, in main
    browser.login()
  File "C:\Python312\AtoZ-Bot.py", line 53, in login
    uname = self.driver.find_element(By.XPATH, "//input[@id='login']")
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 748, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 354, in execute
    self.error_handler.check_response(response)
  File "C:\Python312\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//input[@id='login']"}
  (Session info: chrome=129.0.6668.71); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
        GetHandleVerifier [0x00FA6AB3+25587]
        (No symbol) [0x00F39C54]
        (No symbol) [0x00E32113]
        (No symbol) [0x00E76F62]
        (No symbol) [0x00E771AB]
        (No symbol) [0x00EB7852]
        (No symbol) [0x00E9ABE4]
        (No symbol) [0x00EB5370]
        (No symbol) [0x00E9A936]
        (No symbol) [0x00E6BA73]
        (No symbol) [0x00E6C4CD]
        GetHandleVerifier [0x01284C63+3032483]
        GetHandleVerifier [0x012D6B99+3368153]
        GetHandleVerifier [0x01038F62+624802]
        GetHandleVerifier [0x010407DC+655644]
        (No symbol) [0x00F4260D]
        (No symbol) [0x00F3F6D8]
        (No symbol) [0x00F3F875]
        (No symbol) [0x00F31CA6]
        BaseThreadInitThunk [0x76EA7BA9+25]
        RtlInitializeExceptionChain [0x77DDC11B+107]
        RtlClearBits [0x77DDC09F+191]

**Comment by Amazon-Hate-it-But-Need-it** [comment]
Change the URL in the code to: "https://atoz-login.amazon.work/"

**Comment by NeverSleepOnOpportunities** [comment]
@Lauro112 I updated the code. Itshould be working again.

**Comment by Lauro112** [comment]
Hi
I am not able to do it 😊
Can i conatact you in private to help me
Thanks

**Comment by Amazon-Hate-it-But-Need-it** [comment]
> Hi I am not able to do it 😊 Can i conatact you in private to help me Thanks

Did you follow me the updated instructions?
Send me a DM

**Comment by Lauro112** [comment]
I can't send you DM

**Comment by Amazon-Hate-it-But-Need-it** [comment]
> I can't send you DM

Did you folllow the updated instructions?

What is the issue/error?
