### ISSUE TITLE
Xpath error?

### ISSUE THREAD

**Issue by seanv3204** [Amazon-Hate-it-But-Need-it/Amazon-AtoZ-VET-Flex-Bot#2]
was trying my best to fix this error but cant tell if its a timing issue or the change in xpath, im a newbie so bear with me. I think the xpath changed but im not sure, i like to believe it did since i couldnt find the original xpath.
 
Cookies saved successfully at cookies.json.
Traceback (most recent call last):
  File "C:\Users\Admin\Downloads\AtoZ-Bot - Fixed.py", line 183, in <module>
    main()
    ~~~~^^
  File "C:\Users\Admin\Downloads\AtoZ-Bot - Fixed.py", line 175, in main
    browser.find_shifts()
    ~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Admin\Downloads\AtoZ-Bot - Fixed.py", line 110, in find_shifts
    button = self.driver.find_element(By.XPATH, "//button[@data-testid='FindShiftsQuickLink']")
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python313\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 766, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python313\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 380, in execute
    self.error_handler.check_response(response)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python313\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//button[@data-testid='FindShiftsQuickLink']"}
  (Session info: chrome=131.0.6778.70); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
        GetHandleVerifier [0x00DB5093+25075]
        (No symbol) [0x00D3E124]
        (No symbol) [0x00C1BE63]
        (No symbol) [0x00C5FD06]
        (No symbol) [0x00C5FF4B]
        (No symbol) [0x00C9D8C2]
        (No symbol) [0x00C81EC4]
        (No symbol) [0x00C9B48E]
        (No symbol) [0x00C81C16]
        (No symbol) [0x00C53F3C]
        (No symbol) [0x00C54ECD]
        GetHandleVerifier [0x010A2523+3094147]
        GetHandleVerifier [0x010B5754+3172532]
        GetHandleVerifier [0x010ADF32+3141778]
        GetHandleVerifier [0x00E52100+668256]
        (No symbol) [0x00D46C4D]
        (No symbol) [0x00D43DF8]
        (No symbol) [0x00D43F95]
        (No symbol) [0x00D36C80]
        BaseThreadInitThunk [0x764AFCC9+25]
        RtlGetAppContainerNamedObjectPath [0x77DF809E+286]
        RtlGetAppContainerNamedObjectPath [0x77DF806E+238]

**Comment by Amazon-Hate-it-But-Need-it** [comment]
I updated the code. It should be working again.

**Comment by ImRyzer** [comment]
Great. awesome, I see that now, thanks for confirming my suspicions about the whole xpaths, spent awhile trying to fix it and i was close to figuring it out lmao. But thanks again for taking your time out of your day to fix this issue, its working now, its been a massive help in getting shifts, shit is like near impossible to get on my own.
