### ISSUE TITLE
New Issue 

### ISSUE THREAD

**Issue by Lucifer-Meet** [Amazon-Hate-it-But-Need-it/Amazon-AtoZ-VET-Flex-Bot#9]
i have the save the script and ran into the terminal i got this error, 

Traceback (most recent call last):
  File "C:\Users\meetg\AtoZ-Bot.py", line 203, in <module>
    main()
  File "C:\Users\meetg\AtoZ-Bot.py", line 193, in main
    browser.save_cookies()
  File "C:\Users\meetg\AtoZ-Bot.py", line 116, in save_cookies
    json.dump(cookies, open("cookies", "wt", encoding="utf8"))
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
PermissionError: [Errno 13] Permission denied: 'cookies'

**Comment by Amazon-Hate-it-But-Need-it** [comment]
The only things I  can suggest are to run the terminal as administrator/check the directory's permissions.
